const {chromium}=require('/home/claude/work/node_modules/playwright');const fs=require('fs');process.chdir('/home/claude/work');
const LIB={'xlsx.full.min.js':'npmlib/xlsx/package/dist/xlsx.full.min.js','jspdf.umd.min.js':'npmlib/jspdf-2.5.1/package/dist/jspdf.umd.min.js','jspdf.plugin.autotable.min.js':'npmlib/jspdf-autotable-3.8.2/package/dist/jspdf.plugin.autotable.min.js','pdf.min.js':'npmlib/pdfjs/package/build/pdf.min.js','pdf.worker.min.js':'npmlib/pdfjs/package/build/pdf.worker.min.js'};
const out=[];const ok=(c,n)=>{out.push((c?'OK  ':'FALHOU ')+n);console.log((c?'OK  ':'FALHOU ')+n)};
const D='/tmp/claude-0/d2/';fs.mkdirSync(D,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});const ctx=await b.newContext({viewport:{width:1280,height:900},acceptDownloads:true});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route('**/cdnjs.cloudflare.com/**',r=>{const f=r.request().url().split('/').pop();r.fulfill({body:fs.readFileSync(LIB[f]||'package/dist/leaflet.js'),contentType:'application/javascript'})});await p.route(/(jsdelivr|fonts\.g|openstreetmap|arcgisonline)/,r=>r.abort());
await p.goto('http://localhost:8765/#calculadora');await p.waitForTimeout(1200);
await p.setInputFiles('#cSerFile','/tmp/claude-0/apj/apontamentos_BR-277.json');await p.waitForSelector('#cSerMsg .sermsg b',{state:'attached'});
const calc=async(ka,kb,pi,se)=>{await p.fill('#cKmA',ka);await p.fill('#cKmB',kb);await p.selectOption('#cPista',pi);await p.selectOption('#cSent',se);await p.click('#cForm button[type=submit]');await p.waitForTimeout(500)};
const KA=process.env.KA||'196+000',KB=process.env.KB||'197+000',SE=process.env.SE||'ALL';
await p.selectOption('#rfEquipe','Dreno Sandro');await p.waitForTimeout(300);await calc(KA,KB,'DRN',SE);
await p.fill('#rfData','2026-10-09');await p.selectOption('#rfObra','Restauração BR-277 – Blocos 02 e 03');await p.selectOption('#rfEquipe','Dreno Sandro');await p.dispatchEvent('#rfEquipe','change');
ok(await p.isVisible('#rfUsiSet'),'pergunta de usinagem aparece para equipe de dreno');
for(const [id,v] of [['rfUPrep','04:00'],['rfUIni','04:30'],['rfSCafe','04:30'],['rfSDds','05:00'],['rfSSai','05:30'],['rfECafe','04:30'],['rfEDds','05:00'],['rfESai','05:30'],['rfTempoMsg','A previsão do tempo está estável. Seguiremos monitorando.']])await p.fill('#'+id,v);
await p.selectOption('#rfTempo','Ensolarado');
await p.click('#cRep');await p.waitForTimeout(300);ok(/Haverá usinagem/.test(await p.textContent('#rfPend'))&&(await p.isHidden('#repView')),'sem Sim/Não não emite: '+(await p.textContent('#rfPend')));
await p.screenshot({path:D+'form_pend.png'});
await p.check('input[name=rfUsiDr][value=S]');ok(await p.isVisible('#rfUsiQt'),'Sim mostra a quantidade');
await p.click('#cRep');await p.waitForTimeout(200);ok(/Quantidade prevista/.test(await p.textContent('#rfPend')),'quantidade obrigatória');
await p.fill('#rfUsiQt','0');await p.click('#cRep');await p.waitForTimeout(200);ok(/maior que zero/.test(await p.textContent('#rfPend')),'zero recusado');
await p.fill('#rfUsiQt','12,5');await p.screenshot({path:D+'form_sim.png'});await p.click('#cRep');await p.waitForTimeout(1000);ok(!(await p.isHidden('#repView')),'emitido com Sim e 12,5 t');
await p.click('.rtype button[data-rt="simp"]');await p.waitForTimeout(600);
let t=await p.textContent('#repDoc');ok(/Usinagem para dreno/.test(t)&&/SIM/.test(t)&&/12,50 t/.test(t),'quadro Usina: SIM e 12,50 t');
const segs=await p.$$eval('.sdb',a=>a.map(x=>({h:x.querySelector('.sdh').innerText.replace(/\s+/g,' '),k:[...x.querySelectorAll('.sdg span')].map(s=>s.textContent),none:!!x.querySelector('.sdn')})));
console.log(JSON.stringify(segs.map(s=>[s.h,s.k.length,s.k.slice(0,4),s.none])));
const qtd=await p.$$eval('.sr-t td.q.c',a=>a.map(x=>+x.textContent));const tile=await p.$$eval('.sr-sum div',a=>a.map(x=>x.innerText.replace(/\s+/g,' ')).find(x=>/Saídas de dreno/i.test(x)));
ok(qtd.length===segs.length&&qtd.every((n,i)=>n===segs[i].k.length),'coluna Qtd. de saídas = estacas da grade '+qtd);ok(tile&&+tile.match(/\d+$/)[0]===qtd.reduce((a,b)=>a+b,0),'cartão Saídas de dreno = soma: '+tile);
const all=segs.flatMap(s=>s.k);ok(new Set(all).size===all.length,'sem estacas repetidas');
const num=k=>{const [a,b]=k.split('+');return +a*1000+ +b};ok(segs.every(s=>{const dec=/Decrescente/.test(s.h),v=s.k.map(num);return v.every((x,i)=>!i||(dec?x<v[i-1]:x>v[i-1]))}),'estacas em ordem do sentido');
ok(segs.filter(s=>!s.k.length).every(s=>s.none),'segmento sem saídas mostra o aviso');
await p.screenshot({path:D+'simp.png',fullPage:true});
let dl=p.waitForEvent('download',{timeout:60000});await p.click('#rvPng');await (await dl).saveAs(D+'simp_sim.png');
dl=p.waitForEvent('download',{timeout:60000});await p.click('#rvPdf');await (await dl).saveAs(D+'simp_sim.pdf');
await p.click('.rtype button[data-rt="full"]');await p.waitForTimeout(900);await p.evaluate(()=>document.querySelector('.sdx').scrollIntoView());await p.waitForTimeout(200);await p.screenshot({path:D+'full.png'});
dl=p.waitForEvent('download',{timeout:60000});await p.click('#rvPdf');await (await dl).saveAs(D+'full_sim.pdf');
const reg=await p.evaluate(()=>JSON.parse(localStorage.getItem('br277.execProgs')).find(x=>x.data==='2026-10-09'));ok(reg.usiDr==='S'&&reg.usiQt===12.5,'programação salva com usinagem S / 12.5');
// editar: Não
await p.click('#rvEdit');await p.waitForTimeout(400);ok(await p.isChecked('input[name=rfUsiDr][value=S]')&&(await p.inputValue('#rfUsiQt'))==='12,5','Editar dados traz Sim e 12,5');
await p.check('input[name=rfUsiDr][value=N]');ok(await p.isHidden('#rfURow')&&await p.isHidden('#rfUsiQtF'),'Não oculta horários da usina e a quantidade');await p.screenshot({path:D+'form_nao.png'});
await p.evaluate(()=>document.getElementById('rfUPrep').value='');await p.click('#cRep');await p.waitForTimeout(300);console.log('PEND',await p.textContent('#rfPend'),await p.isHidden('#rfPend'));await p.waitForTimeout(1000);ok(!(await p.isHidden('#repView')),'emitido com Não sem horários da usina');
await p.click('.rtype button[data-rt="simp"]');await p.waitForTimeout(600);t=await p.textContent('.sr-us');ok(/NÃO/.test(t)&&!/Preparação|Quantidade|Início/.test(t),'quadro Usina: só NÃO ('+t.replace(/\s+/g,' ')+')');
dl=p.waitForEvent('download',{timeout:60000});await p.click('#rvPng');await (await dl).saveAs(D+'simp_nao.png');
dl=p.waitForEvent('download',{timeout:60000});await p.click('#rvPdf');await (await dl).saveAs(D+'simp_nao.pdf');
await p.click('.rtype button[data-rt="full"]');await p.waitForTimeout(600);dl=p.waitForEvent('download',{timeout:60000});await p.click('#rvPdf');await (await dl).saveAs(D+'full_nao.pdf');
// equipe de pavimentação: sem pergunta
await p.click('#rvEdit');await p.waitForTimeout(300);await p.selectOption('#rfEquipe','Pavimentação Johonatan');await p.dispatchEvent('#rfEquipe','change');ok(await p.isHidden('#rfUsiSet'),'pavimentação: sem pergunta de usinagem');
ok(errs.length===0,'sem erros JS '+JSON.stringify(errs.slice(0,3)));fs.writeFileSync(D+'rep.txt',out.join('\n'));await b.close()})();
